# Generated by Django 4.2.9 on 2024-11-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_user_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.category'),
        ),
    ]
