# Generated by Django 5.0.6 on 2024-09-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
